language: c
sudo: false
notifications:
  email:
    - tbekolay@gmail.com

env:
  global:
    - PYTHON="3.5.2"

matrix:
  include:
    - env: MODE="test"
    - env: MODE="static"
    - env: MODE="docs"

before_install:
  - source .ci/conda.sh install

install:
  - .ci/$MODE.sh install

script:
  - .ci/$MODE.sh script

after_success:
  - .ci/$MODE.sh after_success
